// RootLayout.tsx

import "@/app/globals.css";
import Head from "next/head";
import ComponentLayout from "@/Components/ComponentLayout";

export const metadata = {
  title: "Usefun Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      </Head>
      <body className=" h-screen UI-Ecommerce flex">
        <ComponentLayout />
        <main className="bg-netral-20/50 w-full min-h-screen overflow-scroll mt-[92px]">
          {children}
        </main>
      </body>
    </html>
  );
}
